server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/huji.p12
    key-alias: huji
    key-store-password: ${KEY_STORE_PASSWORD}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/huji"
    username: "huji"
    password: "Password123?#"
