---
spring:
  application:
    name: "api"
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

# springdoc configuration
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs

# actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,info"

huji:
  security:
    jwt:
      signing-key: ${HUJI_SECURITY_JWT_SIGNING_KEY}
      expiration-in-seconds: 3600
