version: "3"

services:
  postgresql:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=huji
      - POSTGRES_PASSWORD=Password123?#
      - POSTGRES_DB=huji
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data