# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Web CI

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
      - "./github/workflows/web-ci.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - "./github/workflows/web-ci.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install
        working-directory: ./web
        run: npm ci
      - name: Run test
        working-directory: ./web
        run: npm test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: web-test-report
          path: ./web/coverage
